# Generated by Django 2.2.28 on 2026-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Look at me!', max_length=500),
            preserve_default=False,
        ),
    ]
