# Generated by Django 2.2.28 on 2026-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0002_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
