# Generated by Django 2.2.28 on 2026-03-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0002_auto_20260327_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='profile',
            new_name='author',
        ),
    ]
