# Generated by Django 2.2.28 on 2026-03-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0002_postlike_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_likes', to='mybase.Topic'),
        ),
    ]
