# Generated by Django 2.2.28 on 2026-03-28 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0003_auto_20260327_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.Page'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.Topic'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mybase.Topic'),
        ),
    ]
