# Generated by Django 2.2.28 on 2026-03-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0004_auto_20260328_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mybase.Page')),
            ],
        ),
        migrations.CreateModel(
            name='TopicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mybase.Topic')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.PostHistory'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='topic_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.TopicHistory'),
        ),
    ]
