# Generated by Django 2.2.28 on 2026-03-28 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0004_auto_20260328_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 21, 57, 20, 530667, tzinfo=utc)),
        ),
    ]
