# Generated by Django 2.2.28 on 2026-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0005_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
