# Generated by Django 2.2.28 on 2026-03-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0006_auto_20260326_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='body',
        ),
    ]
