# Generated by Django 2.2.28 on 2026-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
