# Generated by Django 2.2.28 on 2026-03-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0009_auto_20260327_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
