# Generated by Django 2.2.28 on 2026-03-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0010_remove_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
